### ISSUE TITLE
Counter not reseted

### ISSUE THREAD

**Issue by Octachore** [ThomasKerbrat/mines#1]
**Problem**
When clicking on _Rejouer_ when the game is not finished, the counter continues to run.

**Steps to reproduce**

1. Start a game and wait a few seconds (make sure it's not finished, i.e. won or loose)
2. Click on _Rejouer_

**May (or may not) be related**

1. Start a game
2. Click _Pause_
3. Click _Rejouer_

The counter is reseted but the button _Continuer_ is still available (throws _TypeError: Cannot read property 'isPaused' of null_ when clicking on it).

**Comment by ThomasKerbrat** [comment]
Thank you very much 👍
